In [1]:
# numpy : 수치 데이터 -> 다차원 배열 구조 ndarray, 행렬 연산
# pip install numpy

In [ ]:
import numpy as np

In [3]:
np.__version__

'1.21.4'

In [8]:
#list를 numpy array로 변환
ar1 = np.array([1,2,3,4,5])
ar1

array([1, 2, 3, 4, 5])

In [17]:
ar1.shape

(5,)

In [9]:
type(ar1)

numpy.ndarray

In [12]:
ar2 = np.array([[10,20,30], [40,50,60]])
ar2

array([[10, 20, 30],
       [40, 50, 60]])

In [18]:
ar2.shape

(2, 3)

In [20]:
ar3 = np.arange(1,11,2)
ar3

array([1, 3, 5, 7, 9])

In [22]:
ar4 = np.array([1,2,3,4,5,6]).reshape((3,2))
ar4

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
ar5 = np.zeros((2,3))
ar5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
ar6 = ar2[0:2,0:2]
ar6

array([[10, 20],
       [40, 50]])

In [25]:
ar7 = ar2[0,:]
ar7

array([10, 20, 30])

In [27]:
ar8 = ar1+10
ar8

array([11, 12, 13, 14, 15])

In [28]:
ar8 - ar1

array([10, 10, 10, 10, 10])

In [29]:
ar1 * 2

array([ 2,  4,  6,  8, 10])

In [30]:
ar1 / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [31]:
# 행렬 곱 연산
ar9 = np.dot(ar2, ar4)
ar9

array([[220, 280],
       [490, 640]])